# Data Collection
collection:
  historical_days: 90
  samples_per_day: 5
  max_retries: 3
  batch_size: 1000

# Chains to Monitor
chains:
  - name: "ethereum"
    min_block: 0
    include_mempool: true
  - name: "near"
    min_block: 0
    include_mempool: true
  - name: "solana"
    min_block: 0
    include_mempool: true
  - name: "avalanche"
    min_block: 0
    include_mempool: true

# DeFi Protocols
protocols:
  - name: "uniswap"
    version: "v3"
    min_tvl: 1000000  # $1M minimum TVL
  - name: "aave"
    version: "v3"
    min_tvl: 1000000
  - name: "curve"
    version: "v2"
    min_tvl: 1000000

# Data Processing
processing:
  min_transaction_value: 100  # $100 minimum transaction value
  exclude_contracts: true     # Exclude contract-to-contract transactions
  group_by: "1h"             # Aggregate data hourly
  clean_outliers: true       # Remove statistical outliers
  fill_missing: "ffill"      # Forward fill missing values

# Synthetic Data Generation
synthetic:
  min_quality_score: 0.8
  max_attempts_per_sample: 2
  temperature_range: [0.5, 0.8]
  batch_size: 10
  max_concurrent_requests: 5
  retry_delay_seconds: 1

# Dataset Split
split:
  train: 0.8
  validation: 0.1
  test: 0.1
  random_seed: 42

# Storage
storage:
  compression: "gzip"
  format: "jsonl"
  backup: true
  version_control: true
  max_versions: 5

# Market metrics to collect from Flipside
metrics:
  - num_txs                  # Daily transaction count
  - total_volume            # Total transaction volume
  - unique_users            # Daily active users
  - avg_tx_value            # Average transaction value
  - tx_volatility_7d        # 7-day transaction volatility
  - txn_growth_pct_7d       # 7-day transaction growth
  - user_growth_pct_7d      # 7-day user growth
  - gas_used                # Total gas used
  - success_rate            # Transaction success rate

# Quality thresholds for synthetic data
quality:
  min_score: 0.7            # Minimum quality score (0-1)
  required_components:
    - data_citations        # Must include proper data citations
    - calculations          # Must show calculation steps
    - confidence_intervals  # Must include confidence intervals
    - market_analysis       # Must provide market analysis

# Generation parameters
generation:
  max_retries: 3            # Maximum retries per example
  batch_size: 10            # Number of examples to generate in parallel
  temperature: 0.7          # Temperature for text generation
  max_tokens: 1000          # Maximum tokens per response 